version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./insectia:/insectia
    ports:
      - "8000:8000"
    depends_on:
      - db
  
networks:
  default:
    name: insectia
