# Generated by Django 4.2.4 on 2023-09-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='insectimage',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insectimage',
            name='predicted_class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
